### PR TITLE
Spec: modify description, add chum metadata

### PR DESCRIPTION
**Pull request by nephros**
See https://forum.sailfishos.org/t/announcing-sailfishos-chum-gui-0-3/9839/29 and https://github.com/sailfishos-chum/main/blob/main/Metadata.md for the chum metadata information.

### CODE REVIEW

**Comment by Olf0** [comment]
This is looking fine, although starting the `%desc` line with a lowercase letter looks very unusual to me.

We can try including the extant icon, maybe `QML icon` is able to render it (modern browsers are not):
```
…
Custom:
  Repo: https://github.com/…
Icon: https://raw.githubusercontent.com/sailfishos-patches/patchmanager/master/src/icons/svgs/icon-m-patchmanager2.svg`
…
```

BTW, including an `raw.githubusercontent.com/` (similarly at Gitlab) link is crucial, as [Rinigus tried to point out](https://forum.sailfishos.org/t/announcing-sailfishos-chum-gui-0-3/9839/28).  Some of your [packages at GitLab still throw errors](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/7#issuecomment-1011565487) (see point **vii.**), because they do use "non-raw" links to icons:
```
[W] unknown:17 - file:///usr/share/sailfishos-chum-gui/qml/components/PackagesListItem.qml:17:5: QML Image: Error decoding: https://gitlab.com/nephros/harbour-imagemagick/-/blob/obs/files/icon-imagemagick_sfos_256.png: Unsupported image format
[W] unknown:17 - file:///usr/share/sailfishos-chum-gui/qml/components/PackagesListItem.qml:17:5: QML Image: Error decoding: https://gitlab.com/nephros/openrepos-nethogs/-/blob/obs/rpm/nethogs_512.png: Unsupported image format
[W] unknown:17 - file:///usr/share/sailfishos-chum-gui/qml/components/PackagesListItem.qml:17:5: QML Image: Error decoding: https://gitlab.com/nephros/openrepos-nload/-/blob/obs/rpm/nload_512.png: Unsupported image format
```
IIRC there is a way, but by clicking around at GitLab I failed to find it (would need to read documentation or search the Web).

**Review by Olf0 — CHANGES_REQUESTED** [review]
May I suggest to adapt these changes to the current wording style:

`Summary:    manages Patches for SailfishOS`

and
```
%description
Patchmanager is a tool for transparently modifying installed files by the patch
utility and for managing the special Patches for doing so.  Since version 3.0
it does not modify original files, but alters their content when they are loaded
into RAM to be run.
```

**Comment by nephros** [comment]
> This is looking fine, although starting the `Summary` line with a lowercase letter looks very unusual to me. Is this required or advised somewhere?

No, just mentioning (repeating) the package name is complained about by RPMlint.
 
> You can also try including the extant icon, maybe `QML icon` is able to render it (modern browsers are not):
> 
> ```
> …
> Custom:
>   Repo: https://github.com/…
> Icon: https://raw.githubusercontent.com/sailfishos-patches/patchmanager/master/src/icons/svgs/icon-m-patchmanager2.svg`

The link style is straight from the Chum Wiki example - should work in chum-gui. But I'll switch it to ./src/plugin/icon-m-patchmanager.png anyway.

> BTW, including an `raw.githubusercontent.com/` (similarly at Gitlab) link is crucial, as [Rinigus tried to point out](https://forum.sailfishos.org/t/announcing-sailfishos-chum-gui-0-3/9839/28). Some of your [packages at GitLab still throw errors](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/7#issuecomment-1011565487) (see point **vii.**), because they do use "non-raw" links to icons:

I am aware, but there's only so much time - also I want to spare the chum guys from too many trivial reqests to approve. It will come.

> IIRC there is a way, but by clicking around at GitLab I failed to find it (would need to read documentation or search the Web).

There's a "raw" button when viewing binary (or rather any type of) files.

**Comment by nephros** [comment]
> May I suggest to adapt these changes to the current wording style:
> 
> `Summary: manages Patches for SailfishOS`
> 
> and
> 
> ```
> %description
> Patchmanager is a tool for transparently modifying installed files by the patch
> utility and for managing the special Patches for doing so.  Since version 3.0
> it does not modify original files, but alters their content when they are loaded
> into RAM to be run.
> ```

Fine!
BTW that text is straight from the Openrepos page, so may be you want to update it there as well.

> P.S.: I intended to commit to an own branch in my repository, but failed to. Then I thought, "WTF, lets try straight ahead" and expected that to fail and it looked like it. But now I see that I successfully committed that in your branch (and realise my syntax error, before). Feel free to revert it, if you do not like it, it was rather "wild clicking late at night in frustration".

"Allow updates by maintainers" magic!

**Comment by nephros** [comment]
In (maybe) closing, thank you Olf for your very thourough review (here and elsewhere).

**Review by Olf0 — APPROVED** [review]
Looking fine!

**Comment by Olf0** [comment]
> Fine! BTW that text is straight from the Openrepos page, so may be you want to update it there as well.

Ah, that is why they felt so familiar. :wink:

> > P.S.: I intended to commit to an own branch in my repository, but failed to. Then I thought, "WTF, lets try straight ahead" and expected that to fail and it looked like it. But now I see that I successfully committed that in your branch (and realise my syntax error, before). Feel free to revert it, if you do not like it, it was rather "wild clicking late at night in frustration".
> 
> "Allow updates by maintainers" magic!

Yeah, but for the next non-trivial review-changes I will try again to suggest changes in a branch in my repo, instead of committing directly to yours (even if I am allowed to).

**Pull request merged**
