### PR TITLE
multi-apply-tool: fix some syntax errors

### PR DESCRIPTION
**Pull request by nephros**
It seems the history of #302 ended up in some merge/syntax errors

These are some quick changes to make the script work again.

### CODE REVIEW

**Review by Olf0 — DISMISSED** [review]
Have to review the `export` case again, when less tired.

<sup>P.S.: Oops, this was my mishap(s) starting with [commit f43e8b6 ](https://github.com/sailfishos-patches/patchmanager/pull/302#issuecomment-1079170181).
</sup>

**Review by b100dian — APPROVED** [review]
LGTM. The changes are quite clear with white-space ignoring diff.

**Comment by Olf0** [comment]
Yes, these change were fine, but the double `shift` in lines 75 & 76 is not, and the additional check for sufficient parameters should also be introduced to ´-a´ and ´-d´.

Will do, hopefully tonight.

**Review by Olf0 — COMMENTED** [review]
All fine.

**Pull request merged**
