### PR TITLE
Add new guys to Developer page

### PR DESCRIPTION
**Pull request by nephros**
added myself in the first commit

@Olf0 @b100dian feel free to add your info

### CODE REVIEW

**Comment by b100dian** [comment]
That branch name:)

**Comment by Olf0** [comment]
@nephros, because you are the "UI tweaker", is there a preferred icon size?
Rectangular and between 84x84 and 128x128?
I will add one until Sunday.

P.S.: I also altered @SfietKonstantin's occupation WRT Patchmanager from "Main developer" to "Original developer".

**Comment by nephros** [comment]
> @nephros, because you are the "UI tweaker", is there a preferred icon size? Rectangular and between 84x84 and 128x128? I will add one until Sunday.
> 


Currently the images are displayed in `Theme.iconSizeMedium`, which on my X10 is 112 pixels. Existing files are between 72x72-ish and 256x256. The display on the page is rather small, so even the low-res ones work.

The icon display is a square, and the file should be as well (otherwise it will be scaled or cropped), but transparent PNGs work for round and other shapes.

**Comment by b100dian** [comment]
@Olf0 you still need to add that png file - thanks!

**Comment by Olf0** [comment]
> @Olf0 you still need to add that png file - thanks!

Yes, I know.
Please, walk a bit slower with me.  I have one around in an appropriate size , ... somewhere.

**Comment by nephros** [comment]
> Yes, I know. Please, walk a bit slower with me. I have one around in an appropriate size , ... somewhere.


> I think it's in my basement... let me go upstairs and check.
>  -- M. C. Escher

**Comment by Olf0** [comment]
Great, now that I have established access to my backups and a picture 244x244 Px², the GH-webfrontend tells me:
> **Uploads are disabled.**
File uploads require push access to this repository.

O.K., will fork and pose a MR.

**Comment by nephros** [comment]
> Great, now that I have established access to my backups and a picture 255² Px², the GH-webfrontend tells me:
> 
> > **Uploads are disabled.**
> > File uploads require push access to this repository.

Weird. I thought I had added "access for maintainers".
Anyway I've taken the liberty to commit your image meanwhile.

**Review by Olf0 — APPROVED** [review]
Looking fine.

**Comment by nephros** [comment]
Wohoo! And now we're official!

**Pull request merged**
