### PR TITLE
[pm_apply] Do convert multiple libpath references

### PR DESCRIPTION
**Pull request by Olf0**
Re-do commit b1fea73 (as 9e16ec6) and a fixed version of commit 2a1f08b (as dd1a211) …

### CODE REVIEW

**Comment by Olf0** [comment]
As [mentioned in commit 222](https://github.com/sailfishos-patches/patchmanager/pull/222#issuecomment-1003147926), IMO it is preferable not to squash these two commits, in order to keep the code changes comprehensible and traceable.

**Review by nephros — APPROVED** [review]
Finally got around to testing, works fine, thanks.

I have used the changes from #237 and #228 to test against the test-cases.

@Olf0 whenever you get around to it, please merge #237 either into this, or on top of it.

**Comment by Olf0** [comment]
> @Olf0 whenever you get around to it, please merge #237 either into this, or on top of it.

Commented that one and did merge.
Please review #239, which is based upon and supersedes #238.

And I discovered another ToDo **after** merging #239 into this branch `Olf0-patch-3`:
De-indent the whole function `mangle_libpath` by two space characters.

**Comment by Olf0** [comment]
See also subsequent PRs  #241 and #242.

**Pull request merged**
