### PR TITLE
Update dialog.qml

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by Olf0** [comment]
Supposed to supersede PR #46.
@nephros & @b100dian, is that done correctly now, i.e. by only altering <dialog.qml>?

**Review by nephros — APPROVED** [review]

**Comment by nephros** [comment]
Just a general note - the whole translation thing has been in statis for a while so changing things in the source isn't a big deal.
But in general, changing source strings does generate (sometimes unnecessarily) work for the translators.

An alternative to consider is leaving the source strings intact and changing the English translation for them instead.

**Comment by Olf0** [comment]
> Just a general note - the whole translation thing has been in statis for a while so changing things in the source isn't a big deal.

Yes, "stasis" (deep, deep sleep; as frozen or "cryo-sleep").

> But in general, changing source strings does generate (sometimes unnecessarily) work for the translators.

Argl, this is why I did the whole thing in PR #46!
But that was not O.K. either, you even seem to have deleted files in my *local* fork, e.g. https://github.com/Olf0/patchmanager/blob/d386e4d82141911068bb9f56661792221f9eb65b/translations/settings-patchmanager-ca.ts :roll_eyes: 

> An alternative to consider is leaving the source strings intact and changing the English translation for them instead.

No, they are crap, hence that is no alternative here and I will change them.
1. But, AFAIU, I should also introduce these changes to the English translation?  Is that correct?
2. Is that the file https://github.com/sailfishos-patches/patchmanager/blob/Olf0-enhance-dialog.qml/translations/settings-patchmanager.ts
3. Or is it https://github.com/sailfishos-patches/patchmanager/blob/Olf0-enhance-dialog.qml/translations/settings-patchmanager-en.ts
4. Or maybe https://github.com/sailfishos-patches/patchmanager/blob/Olf0-enhance-dialog.qml/src/qml/settings-patchmanager.ts

To be honest, I am a fed up with that Transifex shit: It seems to generate far more issues than it solves!

Please provide some guidance:
1. {Yes|No}
Plus at most two out of {2|3|4}.

Thanks!

**Comment by nephros** [comment]
About the deletion:

Those files were empty and useless, they just were there because someone added them in Transifex but no one ever did any translation in them.  
That's why I cleaned them from the tree in an earlier commit.

That then caused a "merge conflict" in your PR, so I cleaned them there as well. And the way that is done is by pushing to the original branch - you enabled that option by "allowing edits by maintainers".

Feel free to revert to reset that commit - but really the files involved are not useful to anyone.

And if you prefer I can do changes like that by submitting a PR against your fork - but that will mean more work for you for no real benefit.

**Comment by Olf0** [comment]
> About the deletion:

No need for these many words, ... guess why I started anew here.

But really helpful would be clear answers to my specific questions:
> > Please provide some guidance:
> > 1. 3 or {2|4}?
> > 2. - 4. I.e., at most two out of {2|3|4}!
> > 5. I have the impression, I shall also delete file 4 to avoid further confusion: Is that assumption correct?

Or was that your way of saying "I have no idea"?

**Comment by Olf0** [comment]
Merged to avoid further confusion.
As @b100dian said: Step-by-step.

Still answers to my questions [here]((original source strings, source string file, translated strings files)) and [there](https://github.com/sailfishos-patches/patchmanager/pull/46#issuecomment-933027718) are needed for me to carry out the next steps.

**Comment by nephros** [comment]
> Or was staying mum about these your way of saying "I have no idea" (i.e. CODeRUS & Jolla style)? 

I like keeping conversation in PRs concise and to the point. Answering "I don't know" doesn't add anything, "I'm researching and come back with more information" doesn't either compared to actually coming back with the information later.  
Also these questions have been asked in several places already, and we both know @b100dian is working on it.

PR conversations aren't instant messaging, things don't *have* to be resolved *immediately*.  

I answered the deletion thing first because you seemed irritated so I wanted to resolve it quickly because things like this can escalate. It would seem I did not succeed.

> Side note: I perceive that as passive-aggressive, which is fostered by your ["pun-intended" jokes](https://github.com/sailfishos-patches/patchmanager/pull/69#issuecomment-932996620).

I understand how frustrating conversations with the people who mentioned can be, and you have been very vocal and verbose here and in other places about it. I get it.  
Please don't insinuate or project. I made a joke. That is all.

**Comment by nephros** [comment]
For sake of completeness, my answer to the questions:

> Argl, this is why I did the whole thing (original source strings, source string file, translated strings files) in PR #46! But that was not O.K. either, you even seem to have deleted files in my _local_ fork, e.g. 
> 1. But AFAIU, I should also introduce these changes to the English translation (which is file 3)?  Is that correct?  Or do you mean the "to the strings source file", of which we have two: See files 2 and 4, below.
> 2. Is that the file https://github.com/sailfishos-patches/patchmanager/blob/Olf0-enhance-dialog.qml/translations/settings-patchmanager.ts
> 3. Or is it https://github.com/sailfishos-patches/patchmanager/blob/Olf0-enhance-dialog.qml/translations/settings-patchmanager-en.ts
> 4. Or maybe https://github.com/sailfishos-patches/patchmanager/blob/Olf0-enhance-dialog.qml/src/qml/settings-patchmanager.ts
> 

> Please provide some guidance: 1. 3 or {2|4}? 2. - 4. I.e., at most two out of {2|3|4}! 5. I have the impression, that I shall also delete file 4 to avoid further confusion: Is that assumption correct?


I quite certain from what I know about Qt translation, and that other translation site I have used that:

File 2. Should not be touched by a human at all. This must be generated from the source code by using the `lupdate` tool, after changes were made to the source strings in the original source code files.
File 3. Is the result of the translation process (however it is set up) for the English language. So "translations" of the strings in 2. should go there. It is still open whether that should/can be done in the git repo though. For that we don't know the Weblate process well enough yet.
File 4. seems to be superfluous, no idea why it's there and if it's used for anything.

So my answer to your topmost question: If what you want to change is the source strings, edit the source code files, and run `lupdate` which will put your changes in File 2.  
If at one point you want to do the thing I suggest in #issuecomment-932996014, edit File 3.

For Reference: [Qt Linguist Manual](https://doc.qt.io/qt-5/qtlinguist-index.html)

**Comment by Olf0** [comment]
> PR conversations aren't instant messaging, things don't have to be resolved immediately.

This was the most important statement for me, because I felt well pushed a couple of times, e.g. per PR #69.

So I will let things run its course, @b100dian will run `lupdate` some time and I already suggested [further janitorial work for the translations](https://github.com/sailfishos-patches/patchmanager/pull/46#issuecomment-933113508), only that I probably should not carry out these tasks.

**Comment by nephros** [comment]
> > PR conversations aren't instant messaging, things don't have to be resolved immediately.
> 
> This was the most important statement for me, because I felt well pushed a couple of times, e.g. per PR #69.

I feel you.
Myself I'm a bit obsessed by this project right now, so I try to do a lot of stuff. I know that might change quickly in the future when something else moves into my focus.  
I also felt overwhelmed by finding > 10 emails each morning about activity here, that can give the feeling that you're not keeping up.  
But it's not true. We have git, we have Github, things will not go away just because you don't deal with them *now*.


I appreciate your attention to detail, your persistence, insisting that things that are *wrong* should get *righted*. Those are good traits to have in the project.

But I feel it's useful to keep in mind that all this is not *that* important. Quality over quantity, and most of all, working on this stuff should be *fun*, it is a hobby!  
Which means, work on stuff like to do, and on stuff you can do. Everything else ignore - someone will come along to do it if it's important enough.

Cheers, and good night :)

**Pull request merged**
