### PR TITLE
spec file: beautify, indent & expand

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by Olf0** [comment]
Sorry, that afterthought came too late for the last spec file commit.

**Comment by Olf0** [comment]
I hope and assume that [commit `e19dc99`](https://github.com/sailfishos-patches/patchmanager/pull/285/commits/e19dc99cc6246afc47ee44aeae391e87f30d07cb) does not [make `rpmlint` complaining more, again](https://github.com/sailfishos-patches/patchmanager/pull/231#issuecomment-1012850134), because only parts of the `Summary:` field are repeated in the `%description` section.

**Comment by nephros** [comment]
> I hope and assume that [commit `e19dc99`](https://github.com/sailfishos-patches/patchmanager/pull/285/commits/e19dc99cc6246afc47ee44aeae391e87f30d07cb) does not [increase `rpmlint`'s complaints again](https://github.com/sailfishos-patches/patchmanager/pull/231#issuecomment-1012850134), because with this commit only parts of the `Summary:` field are repeated in the `%description` section.

Ah but it will, rpmlint does not want the package name to be contained in the Summary line.

**Comment by Olf0** [comment]
Ah, that was the point (sorry, I forgot the specifics): I will change that back.

**Pull request merged**
