### PR TITLE
Missed to increase version for ~3.2.3~, now 3.2.4

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by Olf0** [comment]
@nephros, damn, spoilt 3.2.3!  Next try as 3.2.4, please mark as reviewed.

**Review by Olf0 — COMMENTED** [review]
LGTM

**Review by nephros — APPROVED** [review]

**Comment by nephros** [comment]
Nice PR number for the subject btw.

**Comment by nephros** [comment]
Alternatively we can also force-move the tag so version/release history remains gapless.

**Comment by Olf0** [comment]
> Alternatively we can also force-move the tag so version/release history remains gapless.

I do not think this is crucial, it happens regularly (e.g., the second last release of the SailfishOS:Chum GUI application; wasn't me) and generally I think a (incorrectly) set git-tag should rather stay (and be superseded by a new one) than force-moved.  Only if the wrong tag can cause mishaps, I prefer the latter.

**Comment by Olf0** [comment]
@nephros, @b100dian, if you want to try / test PM 3.2.4, it is at [SailfishOS:Chum-testing](https://build.merproject.org/package/show/sailfishos:chum:testing/patchmanager).  I would prefer (minimalistic) feedback by someone, before I push it to SailfishOS:Chum and OpenRepos.

**Comment by b100dian** [comment]
I tested the chum version, installed, unapplied a patch, rebooted.. Seems fine.

**Comment by nephros** [comment]
Also tested Chum build.

Seems to work fine so far, but did not test all functionality.

There's a couple of QML warnings fron WebPatchPage, but those have likely been there before. I'll look at them at some point.

**Pull request merged**
