### PR TITLE
Remove qmlplugindump call from spec file

### PR DESCRIPTION
**Pull request by Olf0**
Original title:

Change sed delimiter character from # to @
... because it irritates the syntax highlighter (and me, every time I read it).

### CODE REVIEW

**Comment by nephros** [comment]
While we're here, the .spec also creates an empty `/usr/lib/qt5/qml/org/SfietKonstantin/patchmanager/plugin.qmltypes` file which then is complained about by rpmlint.

Is that file required at all?

**Comment by Olf0** [comment]
> While we're here, that creates an **empty** `/usr/lib/qt5/qml/org/SfietKonstantin/patchmanager/plugin.qmltypes` file which then is complained about by rpmlint.
> 
> Should it be empty? Is that file required at all?

It cannot be *required*, because `qmlplugindump` / `qmlplugindump-qt5` is not installed by default on SailfishOS (in contrast to e.g., RHEL / CentOS 8).
```
[nemo@sailfish ~]$ which qmlplugindump-qt5
[nemo@sailfish ~]$ which qmlplugindump
[nemo@sailfish ~]$ find /usr -name "qmlpl*"  
find: /usr/share/libsailfishkeyprovider: Permission denied
find: /usr/lib/sailfish-fpd: Permission denied
[nemo@sailfish ~]$
```
Documentation: https://doc.qt.io/qtcreator/creator-qml-modules-with-plugins.html#generating-qmltypes-files
Source code (for v5.13.0, we are at v5.6.3): https://code.woboq.org/qt5/qtdeclarative/tools/qmlplugindump/main.cpp.html

**Comment by nephros** [comment]
> > While we're here, that creates an **empty** `/usr/lib/qt5/qml/org/SfietKonstantin/patchmanager/plugin.qmltypes` file which then is complained about by rpmlint.
> > Should it be empty? Is that file required at all?
> 
> It cannot be _required_, because `qmlplugindump` / `qmlplugindump-qt5` is not installed by default on SailfishOS (in contrast to e.g., RHEL / CentOS 8).

Nono, requiring/using it on the build host is fine because that's a build time thing, (in the rpm `%install` phase), not a runtime thing. Hence it is not required on normal systems.


> While PM seems to do fine without this, I do not comprehend what it originally was good for.

I also suspect it's a legacy artefact, but want to make sure that an empty one doesn't actually have *some* effect compared to not having one at all.

**Comment by Olf0** [comment]
> > > While we're here, that creates an **empty** `/usr/lib/qt5/qml/org/SfietKonstantin/patchmanager/plugin.qmltypes` file which then is complained about by rpmlint.
> > > Should it be empty? Is that file required at all?
> > 
> > It cannot be _required_, because `qmlplugindump` / `qmlplugindump-qt5` is not installed by default on SailfishOS (in contrast to e.g., RHEL / CentOS 8).
> 
> Nono, requiring/using it on the build host is fine because that's a build time thing, (in the rpm `%install` phase), not a runtime thing. Hence `qmlplugindump` is not required on normal systems.

Oh, sorry I did not look close enough this time.

> > While PM seems to do fine without this, I do not comprehend what it originally was good for.
> 
> I also suspect it's a legacy artefact, but want to make sure that an empty one doesn't actually have _some_ effect compared to not having one at all.

IMO it would also be helpful to understand what the original purpose / intention was: That is why I provided the documentation links to the Qt-experts. :wink:

**Comment by nephros** [comment]
> > I also suspect it's a legacy artefact, but want to make sure that an empty one doesn't actually have _some_ effect compared to not having one at all.
> 
> IMO it would also be helpful to understand what the original purpose / intention was: That is why I provided the documentation links to the Qt-experts. 😉

Well, from https://doc.qt.io/qt-5/qtqml-modules-qmldir.html#writing-a-qmltypes-file:

> As such qmltypes files have no effect on the functionality of a QML module. Their only use is to allow tools such as Qt Creator to provide code completion, error checking and other functionality to users of your module.

Therefore I think we can drop the whole thing - or relocate  the file to a -devel package.

**Comment by nephros** [comment]
Ok so I looked at this and what happens is:

```
[   54s] + /usr/lib/qt5/bin/qmlplugindump -v -noinstantiate -nonrelocatable org.SfietKonstantin.patchmanager 2.0 /home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml
[   54s] parsing <outputOfQmlimportscanner> skipping org.SfietKonstantin.patchmanager
[   54s] appending dependency QtQuick 2.0
[   54s] appending dependency Sailfish.Silica 1.0
[   54s] appending dependency Nemo.Notifications 1.0
[   54s] appending dependency org.nemomobile.dbus 2.0
[   54s] QQmlComponent: Component is not ready
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:3:1: module "QtQuick" is not installed
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:4:1: module "Sailfish.Silica" is not installed
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:5:1: module "org.nemomobile.dbus" is not installed
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:3:1: module "QtQuick" is not installed
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:4:1: module "Sailfish.Silica" is not installed
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:5:1: module "org.nemomobile.dbus" is not installed
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:3:1: module "QtQuick" is not installed
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:4:1: module "Sailfish.Silica" is not installed
[   54s] file:///home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/loaddependencies.qml:5:1: module "org.nemomobile.dbus" is not installed
[   54s] + true
[   54s] + wc -l /home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-1.219.1.jolla.i386/usr/lib/qt5/qml/org/SfietKonstantin/patchmanager/plugin.qmltypes
[   54s] 0 /home/abuild/rpmbuild/BUILDROOT/patchmanager-3.1.0+obs.20211104140112.68.g7c21dc5-
```

in short, because these components are not available in the build environment e.g. at Openrepos, `qmlplugindump` can not work and the result is an empty file.

**Comment by nephros** [comment]
> in short, because these components are not available in the build environment e.g. at OBS, `qmlplugindump` can not work and the result is an empty file. This likely is less of a problem in not-as-stripped down build environments.

... and trying to fix that in https://github.com/nephros/patchmanager/tree/Olf0-patch-2.1 results in OBS not being able to launch the builder at all (`blocked downloading n dod packages`).

I conclusion I vote for removing the whole file and generation of it.  
Developers who neeed it can generate it themselves.

**Comment by Olf0** [comment]
@nephros, I adapted the title and content to reflect the outcome of your research.

**Review by nephros — APPROVED** [review]

**Pull request merged**
