### PR TITLE
Really stick to new nomenclature, plus …

### PR DESCRIPTION
**Pull request by Olf0**
1. Fix help output in [`src/bin/patchmanager-daemon/main.cpp`, lines 51-61](https://github.com/sailfishos-patches/patchmanager/blob/26eb9bdb175241e6d85562d28b556a852f03aff9/src/bin/patchmanager-daemon/main.cpp#L51-L61).
2. Fix and slightly extend argument evaluation logic in [`src/bin/patchmanager-daemon/patchmanagerobject.cpp`, lines 941-953](https://github.com/sailfishos-patches/patchmanager/blob/26eb9bdb175241e6d85562d28b556a852f03aff9/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L941-L953).
3. For changes due to the new nomenclature, see, e.g., [Patchmanager's Wiki page *Terms-and-wording*, entry *"enable"*](https://github.com/sailfishos-patches/patchmanager/wiki/Terms-and-wording#enable).

### CODE REVIEW

**Comment by Olf0** [comment]
Open question: What is the technical difference between calling 'patchmanager` (old: "run as daemon, new: "Run Patchmanager as daemon")](https://github.com/sailfishos-patches/patchmanager/pull/337/files#diff-81d57483ccc1832b5475dbd44aa2d3564e809494f3f077ddad12c0027fd720deR56) and calling 'patchmanager` (old: "daemonize", new: "Daemonize Patchmanager")](https://github.com/sailfishos-patches/patchmanager/pull/337/files#diff-81d57483ccc1832b5475dbd44aa2d3564e809494f3f077ddad12c0027fd720deR60) and how to express / differentiate that concisely in these two statements?  Currently they sound confusingly similar.

**Comment by nephros** [comment]
> 1. What is the technical difference between calling `patchmanager` and calling `patchmanager --daemon` 

`patchmanager --daemon` is how it is launched from the d-bus service so it backgrounds and starts to accept calls via that service.

Calling `patchmanager` actually does not do anything, it just checks for the root user and refuses to run if it isn't root, otherwise it will just output the help info.

https://github.com/sailfishos-patches/patchmanager/blob/master/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L941

**Comment by Olf0** [comment]
> > 1. What is the technical difference between calling `patchmanager` and calling `patchmanager --daemon`
> 
> `patchmanager --daemon` is how it is launched from the d-bus service so it backgrounds and starts to accept calls via that service.
> 
> Calling `patchmanager` actually does not do anything, it just checks for the root user and refuses to run if it isn't root, otherwise it will just output the help info.
> 
> Therefore I conclude that the first line in the usage output is plain wrong.
> 
> https://github.com/sailfishos-patches/patchmanager/blob/master/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L941

Thanks, this is what I failed to find quickly yesterday night.

> Calling `patchmanager` actually does not do anything, it just checks for the root user and refuses to run if it isn't root, otherwise it will just output the help info.

[Oh, obviously](https://github.com/sailfishos-patches/patchmanager/blob/master/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L972).

> Therefore I conclude that the first line in the usage output is plain wrong.

So I will change it to "Print this help text.", O.K.?

I also think that there should be an option `--help`, which achieves the same.  Currently any unknown argument results in this being sent to the daemon vis D-Bus, printing [D] unknown:0 - void PatchmanagerObject::process() Has arguments, sending D-Bus message and quit.`

Three more things I am considering:
1. I never called `patchmanager-daemon [-a|-u|--unapply-all]`, always used `patchmanager [-a|-u|--unapply-all]`.  AFAICS (and tried) this is wrong.  Hence shall drop the `-daemon` suffix, correct?
2. Document the option `--reset-system` here.  "Fully reset Patchmanager" would be my first take, unless you can easily think of a better or more specific phrase.  I know you once researched what `--reset-system`, if you do not remember, never mind, IMO a very abstract phrase is better than nothing.
3. Conceptually, I always modelled the `patchmanager` command as a CLI front-end for the `patchmanager-daemon`.  I plan to denote that above all options, where it currently solely states `patchmanager-daemon`, which does not make much sense IMO.

**Comment by Olf0** [comment]
Oh, [line 943](https://github.com/sailfishos-patches/patchmanager/blame/master/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L943) should be 
`} else if (args.count() == 2 && args[1] == QStringLiteral("--reset-system")) {`
, right?

**Review by nephros — APPROVED** [review]

**Review by nephros — APPROVED** [review]

**Comment by nephros** [comment]
On the topic of `--reset-system`, I'd much prefer if it stayed undocumented.

It causes a rather radical noninteractive change, (it determines the rpms owning any files changed by patches, download them and force-installs them).

As such it's a legacy from the days before the ld-preload method and unlikely to be needed any more.

**Comment by nephros** [comment]
> Three more things I am considering:
> 
> 1. I never called `patchmanager-daemon [-a|-u|--unapply-all]`, always used `patchmanager [-a|-u|--unapply-all]`.  AFAICS (and tried) calling `patchmanager-daemon` is wrong and yields nothing.  Hence the `-daemon` suffix shall be dropped throughout the help text, correct?
> [...]
> 
> 3. Conceptually, I always modelled the `patchmanager` command as a CLI front-end for the `patchmanager-daemon`.  I plan to denote that above all options, where it currently solely states `patchmanager-daemon`, which does not make much sense IMO.

"There is no Dana. There is only Zuul".

`patchmanager-daemon` does not exist as a binary. It's also not used anywhere in the output AFAICS. Not sure where that is coming from. There is only the source directory called that.  
The `patchmanager` executable can operate in  both (dbus-) daemon and client mode (when called with any option other than `--daemon`).

**Comment by nephros** [comment]
> Even when in client mode, it uses a running daemon instance to actually do anything (triggered by a dbus message).

Heh *except* for `--reset-system` which does not go through dbus.

**Comment by Olf0** [comment]
> […] Even when in client mode, it uses a running daemon instance to actually do anything (triggered by a dbus message).

This is what confused me into guessing that there must be a separate daemon when reading tĥe help text.

> > Even when in client mode, it uses a running daemon instance to actually do anything (triggered by a dbus message).

> Heh *except* for `--reset-system` which does not go through dbus.

… as the [lines 941-947](https://github.com/sailfishos-patches/patchmanager/blob/master/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L941-L947) / [my code-snippet]https://github.com/sailfishos-patches/patchmanager/pull/337#issuecomment-1381981308) show.

Does your approval also cover this code-snippet?  I.e., does it look O.K.?

**Comment by Olf0** [comment]
> There is no ~~Dana~~  `patchmanager-daemon`, there is only ~~Zuul~~ `patchmanager`.

That did ring a bell, but I had no clue which, so I looked it up: O.K., that was in 1984!
Did not know though, that this phrase has become a meme.  IIRC it is one of the truly cool scenes in this movie, but much of it is "Klamauk" (I guess "a whimsy" comes close, but is not really an equivalent).

**Comment by nephros** [comment]
> … as the [lines 941-947](https://github.com/sailfishos-patches/patchmanager/blob/master/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L941-L947) and [my code-snippet](https://github.com/sailfishos-patches/patchmanager/pull/337#issuecomment-1381981308) show.
> 
> Does your approval also cover this code-snippet? I.e., does it look O.K.?

Yep, LGTM.

> … as the [lines 941-947](https://github.com/sailfishos-patches/patchmanager/blob/master/src/bin/patchmanager-daemon/patchmanagerobject.cpp#L941-L947) and [my code-snippet](https://github.com/sailfishos-patches/patchmanager/pull/337#issuecomment-1381981308) show.
> 
> Does your approval also cover this code-snippet? I.e., does it look O.K.?

Yep, LGTM.

**Pull request merged**
