### PR TITLE
[RPM-spec] Increase version to 3.2.1

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by Olf0** [comment]
Necessary to complete milestone 3.2.1, see https://github.com/sailfishos-patches/patchmanager/milestones

**Review by b100dian — APPROVED** [review]

**Comment by b100dian** [comment]
> Thanks @b100dian and a happy new year. If you have some time, I would be glad, if you review my other PRs for v3.2.1: https://github.com/sailfishos-patches/patchmanager/pulls

Tried, but wasn't able to, sorry. I see you folks handed all the changes, that's great! and thank you!

**Comment by Olf0** [comment]
> I see you folks handed all the changes, that's great! and thank you!

No need to *thank* us, but yes, there is no reason for you to worry about having to spare time to support the upcoming v3.2.1 release.  I intended to get accustomed to the procedures at SailfishOS:Chum anyway, thus I might do this rather sooner than later; I set the due date for v3.2.1 to 15. February, but this is not at all a fixed date.

> Tried, but wasn't able to, sorry.

That is absolutely O.K.
If you can spare some time (at any time later), I would really appreciate, if you could use your contact to Andrey to try to [obtain some information WRT PM4](https://github.com/sailfishos-patches/patchmanager/discussions/151).  I would hope for some general guidance how to proceed ("Ditch it" vs. "still has some value") and content ("now irrelevant stuff" vs. "provides progress in areas ABC & XYZ"), but nothing more.  I tried to look at the changes (a single large commit), but really cannot decide, if it makes any sense to invest time to analyse it further, hence some guidance would be helpful.

**Comment by b100dian** [comment]
Of course, least I can do ;) Write few and use Fernschreiber - I've updated the discussion

**Pull request merged**
