### PR TITLE
Split "Allow incompatible Patches" from "Developer Mode"

### PR DESCRIPTION
**Pull request by nephros**
Fixes: #333

### CODE REVIEW

**Comment by nephros** [comment]
Marking as Draft, pending changes requested in #333

**Review by Olf0 — COMMENTED** [review]
I still have my reservations WRT this "easy implementation", [as already denoted](https://github.com/sailfishos-patches/patchmanager/issues/333#issuecomment-1373987714).

I feel I must at least insist on creating a seamless migration from the old `developerMode` setting to the new `strictCompatability` setting (value needs to be negated, something I tried to avoid in my suggestions) in order to avoid negative feedback from many Patchmanager users, when this change is released.

**Comment by nephros** [comment]
@Olf0 sorry, I have the bad habit of using `fixup` and force-push in my "private" forks.
I overwrote one of your commits doing this.

Please hold off any pushes until I take this PR out of Draft mode.

**Comment by Olf0** [comment]
> @Olf0 sorry, I have the bad habit of using `fixup` and force-push in my "private" forks. I overwrote one of your commits doing this.

That is fine: I have the bad habit of committing trivial change right away.

I created another private branch and a MR, but …

> Please hold off any pushes until I take this PR out of Draft mode.

… failed to update it twice: Will wait and continue to analyse docker@GitHub to achieve caching of the many GBs of docker-image data which are downloaded for each CI run.

**Comment by nephros** [comment]
Okay, have not tested it yet, but it *looks* okay. Have at it!

**Comment by nephros** [comment]
migration snippet needs work.

Dropdown is not set to "allow any".

**Comment by Olf0** [comment]
I first hesitated a bit with [the migration logic](https://github.com/sailfishos-patches/patchmanager/pull/334/files#diff-c092975afb5d44c1002edfec699cb52c26bf8df373b6ed0696c0f8da182d889bR58-R66), but I cannot see any better way (and see that my original ideas were abstractly nice, but not implementable with the extant boolean setting `developerMode`; i.e., purely academic).

Hence I have only four minor commits to suggest via [MR \#3](https://github.com/nephros/patchmanager/pull/3).

**Review by Olf0 — APPROVED** [review]
IMO this is basically looking fine.

Still I would love to comprehend these two statements, either by being addressed by some commit or a brief explanation.  But never mind, I am aware these were just two thoughts being denoted late at night.

> migration snippet needs work.

As [stated above](https://github.com/sailfishos-patches/patchmanager/pull/334#issuecomment-1374356211), IMO its basic logic is O.K. and hard to design differently.

> Dropdown is not set to "allow any"

I simply fail to parse this statement, though [had an idea what it may address](https://github.com/sailfishos-patches/patchmanager/pull/334#issuecomment-1374356211).

**Comment by nephros** [comment]
Pls do not merge yet.

While the migration logic is correct, the Combonox does not yet work correctly.

 1. Its menu has only 2 Entries, while the enum has 4. Therefore when selecting 'No Check' a value of 1 is saved where it should be 3.
 2. As the migration logic saves a 3, when loading the combobox it has no value for it, and falls back to -1/undefined, which is equivalent to the first entry in the menu.

I have workarounds for both but must test them first.

**Comment by Olf0** [comment]
> Pls do not merge yet.

I sure won't, it is "your baby" (unless you have ceased to care about).

> While the migration logic is correct, the Combonox does not yet work correctly.
> 
>     1. Its menu has only 2 Entries, while the enum has 4. Therefore when selecting 'No Check' a value of 1 is saved where it should be 3.
> 
>     2. As the migration logic saves a 3, when loading the combobox it has no value for it, and falls back to -1/undefined, which is equivalent to the first entry in the menu.

Thanks for the details.

> I have workarounds for both but must test them first.

I will happily review them, when they are ready.

**Comment by nephros** [comment]
Please see 4a96399.

I decided to do the simple solution, have no gaps in the value list.

I know this results in a slightly weird order of the menu options (Strict - None - Relaxed), if I had to argue this I'd say, 0 is always the default, and the others are sorted in order of decreasing strictness.

Anyway, doing it this way means we need no workarounds, and also no workarounds/migrations needed when new options are added.

I also have removed the planned "Careless" option for now - partly because you pointed out that in current SFOSes, two options would be superfluous, and partly because fine-grainedness of a "relaxed" option can be tuned somewhere else (i.e. an extra tunable) if necessary.

**Review by Olf0 — APPROVED** [review]
This looks fine to me.  So I guess you are all set, now.

**Comment by nephros** [comment]
And like a true evil American Senator, I sneak in an almost unrelated UI fix in 1dc424b as well.

**Comment by Olf0** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&Tab;&Tab;▲
Oh, good catch.&Tab;&Tab;│

**Comment by nephros** [comment]
@olf you asked to not squash your commits in https://github.com/nephros/patchmanager/pull/2 and https://github.com/nephros/patchmanager/pull/3, do you want to keep them when merging this as well?

If yes, I'd clean up and rebase this branch first. If not I´d just squash-merge this as usual.

**Comment by Olf0** [comment]
> @olf you asked to not squash your commits in [nephros#2](https://github.com/nephros/patchmanager/pull/2) and [nephros#3](https://github.com/nephros/patchmanager/pull/3), do you want to keep them when merging this as well?

Well, that is not really worth the effort, hence …

> If yes, I'd clean up and rebase this branch first. If not I´d just squash-merge this as usual.

… "just squash-merge this as usual".

**Pull request merged**
